<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hangfire.AspNetCore" Version="1.8.24" />
        <PackageReference Include="Hangfire.Core" Version="1.8.24" />
        <PackageReference Include="Hangfire.Redis.StackExchange" Version="1.12.0" />
        <PackageReference Include="Humanizer.Core" Version="3.0.10" />
        <PackageReference Include="LazyCache.AspNetCore" Version="2.4.0" />
        <PackageReference Include="MailKit" Version="4.17.0" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.10" />
        <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
        <PackageReference Include="SignalRSwaggerGen" Version="4.9.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
        <PackageReference Include="Stubble.Core" Version="1.10.8" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TheGrid.Data\TheGrid.Data.csproj" />
        <ProjectReference Include="..\TheGrid.Models\TheGrid.Models.csproj" />
        <ProjectReference Include="..\TheGrid.Postgres\TheGrid.Postgres.csproj" />
        <ProjectReference Include="..\TheGrid.Connectors\TheGrid.Connectors.csproj" />
        <ProjectReference Include="..\TheGrid.Connectors.Abstractions\TheGrid.Connectors.Abstractions.csproj" />
        <ProjectReference Include="..\TheGrid.Sqlite\TheGrid.Sqlite.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Templates\UserManagement\SendConfirmationLink.html">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Templates\UserManagement\SendPasswordResetCode.html">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Templates\UserManagement\SendPasswordResetLink.html">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>