version: '3.4'

services:
  thegrid.server:
    image: ${DOCKER_REGISTRY-}thegridserver
    build:
      context: .
      dockerfile: TheGrid.Server/Dockerfile
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: thegrid123
      POSTGRES_DB: thegrid
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    ports:
      - 8080:8080